### ISSUE TITLE
SPI hardware enable

### ISSUE THREAD

**Issue by jgilbert20** [LowPowerLab/DualOptiboot#1]
I just encountered a bug on a project that I traced to DualOptiboot.

The issue was that raw writes to the SPI pins (SK, MO, MI) were not working as expected in the main code. This only occurred on firmware reloads, not during normal power ons making it a particularly devious bug.

I think the issue is that in some situations DualOptiboot exits after loading new firmware but does not disable the SPI pins. 

I fixed the problems by adding this line to my code. Perhaps you should check the codepaths and make sure this is done before the bootloader exits.

  SPCR &= ~_BV(SPE);

**Comment by LowPowerLab** [comment]
Possibly good catch - not really sure without digging but on a soft restart the pins might remain unchanged (vs hard reset where pins are all disabled).
However any sketch should start with setting pins to a known state - is that not the case in your sketch?

Also if im not mistaken `SPCR &= ~_BV(SPE)` just disables the SPI right?

**Comment by jgilbert20** [comment]
In my test-case, if the bootloader had previously been active loading a sketch, pin 13 and 10 had odd behavior even when pinMode(X,OUTPUT) was called in setup() unless SPI was foreceably disabled. Not sure how pin multiplexing works on AVR chips. I suspect that in most cases users never notice because with the flash chip present they will either be re-enabling SPI themselves or ignoring those pins because the flash hardware would intervene... Didn't do a full investigation so just a guess. This behavior did not occur if I removed power to the chip and reconnected it to the FTDI header without loading a new sketch.

Happy to share more setup details of the sketch if useful.

SPCR &= ~_BV(SPE) is the magic that is called when you do an SPI.end() and I assume it disables the SPI hardware.

**Comment by LowPowerLab** [comment]
Could you possibly describe the odd behavior in more detail?

> The issue was that raw writes to the SPI pins (SK, MO, MI) were not working as expected in the main code.

**Comment by jgilbert20** [comment]
At work today. IIRC i was using nearly all GPIO pins to drive a 8x8 matrix display. The code I wrote was optimized to manipulate port registers directly. Code at the start of the sketch set pinMode() to OUTPUTs using the Arduino API. The first time loading a new sketch, one or two of the columns on the 8x8 display would not light, suggesting they were not sinking current. After POR, the behavior disappeared. Once I added the `SPCR &= ~_BV(SPE)`, the pins operated correctly regardless of if I had recently loaded firmware or not. 

I hope this helps, Felix. I do have this circuit board around still but haven't done any work with it in a super long while. I'm slowly moving over to the SAMD21 and SAMD11 architectures. 

```
/***************************************************

   Resistor-less Matrix LED Driver
   Designed for the ATMEGA328p
   note:
   A6 and A7 are only inputs available to the mux in front of the ADC.
   There is no digital hardware behind the pins.
  something screwy happens with pins 0,1,2

  Ports:
  D – for digital pins seven to zero (bank D)
  B – for digital pins thirteen to eight (bank B)
  C – for analogue pins five to zero (bank … C!)

   Looking down at the matrix with the text pointing towards you

   Columns are the ones running parallel to the text. The column nearest
   the text is actually column 1.

   Rows start on the left at row 1. They are perpendicular to the text.

   That means that actually if you are looking at the matrix with the text in front of you
   the rows will appear to be columns, and visca versa.

   curious question -why can we drive colums all at once.. is this just becuase
   we might want to charlieplex in the future..?

           TOP
   Matrix Meaning: C5   C6   C7   C8    R5    R6    R7    R8
   Matrix Pin #  : 16   15   14   13    12    11    10     9
   ATMEGA label  : D2   D11  D10  D09   D8    D7    D6    D5
   at mega pin#  : 2    11   10   09     8     7     6     5
   atmega port   : D2   B4   B3   B2    B1    D7    D6    D5
    Port D 0..7


           BOTTOM
   Matrix Meaning: R1   R2   R3   R4    C1    C2    C3    C4
   Matrix Pin #  : 16   15   14   13    12    11    10     9
   ATMEGA        : 13   12    D4   D3    A0    A1    A2    A3
                   13   12     4    3    14    15    16    17
                   B6   B5    D4   D3    C0    C1    C2    C3
*/


#pragma GCC optimize ("--always-inline")
#pragma GCC optimize ("-O4")

uint8_t displayBuffer[64];
const  int columns[] = {14, 15, 16, 17, 2, 11, 10, 9};
const  int rows[] = {13, 12, 4, 3, 8, 7, 6, 5 };

// pin high
//PORTD |= _BV(3);

// pin low
//PORTD &= ~_BV(3);

inline void fastColHigh( int a )
{

  digitalWrite( columns[a], HIGH );
  return;

  
  switch (a)
  {
    case 0:
      PORTC |= _BV(0);
      break;
    case 1:
      PORTC |= _BV(1);
      break;
    case 2:
      PORTC |= _BV(2);
      break;
    case 3:
      PORTC |= _BV(3);
      break;
    case 4:
      PORTD |= _BV(2);
      break;
    case 5:
      PORTB |= _BV(3);
      break;
    case 6:
      PORTB |= _BV(2);
      break;
    case 7:
      PORTB |= _BV(1);
      break;
  }
}

inline void fastColLow( int a )
{

    digitalWrite( columns[a], LOW );
  return;


  switch (a)
  {
    case 0:
      PORTC &= ~_BV(0);
      break;
    case 1:
      PORTC &= ~_BV(1);
      break;
    case 2:
      PORTC &= ~_BV(2);
      break;
    case 3:
      PORTC &= ~_BV(3);
      break;
    case 4:
      PORTD &= ~_BV(2);
      break;
    case 5:
      PORTB &= ~_BV(3);
      break;
    case 6:
      PORTB &= ~_BV(2);
      break;
    case 7:
      PORTB &= ~_BV(1);
      break;
  }
}

void setup()
{
  // note on the mini matricies, the columns are annodes (+), rows are cathodes (-)

  Serial.begin( 57600 );
  Serial.println( "Starting up..." );

//  for( int i = 2 ; i < 20 ; i++ )
//  {
//    pinMode( i, INPUT );
//   // digitalWrite( i, LOW );
//  }


  // Dual optiboot enables SPI hardware and doesn't disable it. Can cause some problems. 
  SPCR &= ~_BV(SPE);

  for ( int i = 0 ; i < 8 ; i++ ) {
    pinMode( rows[i], OUTPUT  );
    pinMode( columns[i], OUTPUT  );
  }

  for ( int i = 0 ; i < 8 ; i++ )
  {
    digitalWrite( rows[i], HIGH  );
  }

  for ( int i = 0 ; i < 8 ; i++ )
  {
    digitalWrite( columns[i], LOW  );
  }

  for ( int i = 0 ; i < 64 ; i ++ )
  {
    displayBuffer[i] = 0;
  }


 //  delay(1000);

}

unsigned long lastReport = 0;
unsigned long frames = 0;

unsigned long temp = 0;

int x;

void loop()
{

  if ( millis() - lastReport > 1000 )
  {
    Serial.print( "Frame/sec:" );
    Serial.print( (float)(1.0 * frames / millis() * 1000 ));
    Serial.println();
    lastReport = millis();
  }

  frames++;
  // with no other activities, FPS= 244K
  // going pixel at a time, no memory read = FPS = 1613
  // inline declaration didn't make a different
  // switching to port direct for the columns went from 1600->5000 FPS

  for ( int r = 0 ; r < 8 ; r++ )
  {
    digitalWrite( rows[r], LOW  );

    for ( int c = 0 ; c <  8 ; c++ )
    {
      if ( displayBuffer[ r * 8 + c ] > 0 )
        fastColHigh( c );
    }

    for ( int p = 15 ; p >= 0 ; p-- ) {
      for ( int c = 0 ; c <  8 ; c++ ) {
        if ( displayBuffer[ r * 8 + c ] <= p ) {
          fastColLow( c );
        }
        else {
          // need to do this so that timing remains fixed. otherwise, as the matrix lights up, we loose frames.
          fastColHigh( c );
        }
      }
    }

    for ( int c = 0 ; c <  8 ; c++ ) {
      fastColLow( c );
    }

    digitalWrite( rows[r], HIGH  );
  }

  if ( millis() - temp > 100 )
  {
    //  displayBuffer[x] = 0;
    if ( x++ >= 64 )
      x = 0;
    writePixel( x, 15);
    writePixel( x-1, 12);
    writePixel( x-2, 9);
    writePixel( x-3, 8);
    writePixel( x-4, 3);
    temp = millis();
  }
}

void writePixel(uint8_t x, uint8_t val )
{
  if( x < 0 || x > 63 )
    return;
    
  displayBuffer[x] = val;
}
```

**Comment by LowPowerLab** [comment]
Sure helps explain some things, thanks!
Did you try patching Dualoptiboot, or did you just always use the SPI disable code in your sketch?

**Comment by jgilbert20** [comment]
I added the SPI disable code and left it at that. 

Its gotta be a super corner case. How many people would be using dual optiboot AND not using anything on SPI AND using the HW SPI relevant pins for something not SPI? I was only using dual optiboot in the first place because I've bought so many moteinos over the years (they are my go-to project board) that i just got comfortable with it.

**Comment by LowPowerLab** [comment]
Ok here's a quick summary of my findings:

- the 328p DS states that PORTB (spi pins) are tri-stated in a reset - this would happen with a watchdog reset after Dualoptiboot does a firmware reload:
> The Port B pins are tristated when a reset condition becomes active, even if the clock is not running
- Dualoptiboot executes this code every time it runs:
`SPCR |= _BV(MSTR) | _BV(SPE); //enable SPI and set SPI to MASTER mode`
- However during a reset it looks like only the IO registers are set to defaults, SPCR remaining unchanged

So resetting SPCR in the bootloader should be just fine, and to fully undo the bootloader's actions on SPI this code should actually be called:
`SPCR &= ~_BV(SPE) & ~_BV(MSTR);`

I would add that before calling appstart() on [this line](https://github.com/LowPowerLab/DualOptiboot/blob/master/Optiboot.c#L681), which seems to always set SPCR back to 0. Would you like to submit a PR or should I just add this to the source?

**Comment by LowPowerLab** [comment]
I've [added the change](https://github.com/LowPowerLab/DualOptiboot/commit/2171e07593dd521cf1086b68b18392791c449248), closing issue. If there's still any issue please let me know.
