### ISSUE TITLE
Please provide bootloader for 8MHz variant of Moteino

### ISSUE THREAD

**Issue by heresiarch** [LowPowerLab/DualOptiboot#2]
The Bootloaders does not work with the 8MHz variant described here:
[https://lowpowerlab.com/guide/moteino/moteino-8mhz/](url)
Please drop a 8MHz variant of the bootloader here.
It would also be good to describe the Fuse settings in a formal way as document in github instead on various places in the forum or website.

**Comment by LowPowerLab** [comment]
Look more carefully, its there.

**Comment by heresiarch** [comment]
Sorry I did not see the file. Thanks for the response.
