### ISSUE TITLE
SAMD21 Support

### ISSUE THREAD

**Issue by AndrewCarterUK** [LowPowerLab/DualOptiboot#3]
Does this support the SAMD21?

[This line](https://github.com/LowPowerLab/DualOptiboot/blob/master/Optiboot.c#L58) suggests that it doesn't, but I've read that the Moteino M0 supports OTA updating?

Thanks!

**Comment by LowPowerLab** [comment]
It does NOT. This bootloader is for AVR only - specifically atmega328p and atmega1284p.
The MoteinoM0 has a very different bootloader. However that does support transfer of flash image from an optional external FLASH-MEM chip that comes with MoteinoM0.

**Comment by AndrewCarterUK** [comment]
Is the code for this open source and available? If so, could you please provide me a link?

Also, I believe the [documentation on this page](https://lowpowerlab.com/guide/moteino/moteinom0/) might need to be fixed. It implies that DualOptiboot supports the M0.

![image](https://user-images.githubusercontent.com/6486835/61053858-4233b000-a3e6-11e9-97f3-7ea786a22dbd.png)

**Comment by LowPowerLab** [comment]
Source is not open at this time, however the binaries are included in the Boards package.
If you read that page again ... it says:
1) It runs the Arduino ZERO bootloader, an enhanced version to support OTA
2) Bootloader is **_compatible_** with the DualOptiboot.
Never says or implies that the DualOptiboot is running on it.

I hope that's more clear now.

**Comment by AndrewCarterUK** [comment]
Okay, thanks very much!
