### ISSUE TITLE
WDRF bit is not cleared when the watchdog is turned off

### ISSUE THREAD

**Issue by radu-berezan** [LowPowerLab/DualOptiboot#4]
Hi!

While troubleshooting some reset loops occurring when doing soft restarts, I noticed that WDRF is not cleared when turning off the watchdog. WDE is always set when WDRF is set causing a reset loop. Clearing it fixed my problem.

Many thanks for the great code!

```
void watchdogConfig(uint8_t x) {
  if (x == WATCHDOG_OFF)
	MCUSR &= ~(_BV(WDRF));
  WDTCSR = _BV(WDCE) | _BV(WDE);
  WDTCSR = x;
}
```

**Comment by LowPowerLab** [comment]
I just pushed the fix you suggested.
Thanks a lot for reporting this find Radu!
