### ISSUE TITLE
Header description of size bytes

### ISSUE THREAD

**Issue by AaronMcDaniel** [LowPowerLab/DualOptiboot#5]
The header bytes are described as:

"FLXIMG:9999:XXXXXXXXXXX where: ... -'9999' are 4 size bytes indicating how long the new flash image is (how many bytes to read)"

Should these four size bytes be in big or little endian format? Neither of them seem to work on my setup, so I assume that I'm doing something else wrong, but I would like to eliminate this as an issue

**Comment by LowPowerLab** [comment]
You can see how this is decoded in the library code.
It's MSB first. So 23456 bytes = FLX:5BA0:xxxxxx
