### ISSUE TITLE
DualOptiboot fails on arduino pro mini 8 MHz

### ISSUE THREAD

**Issue by hexad** [LowPowerLab/DualOptiboot#7]
I burned the `Dualoptiboot_v5.0_atmega328_8mhz_57600baud_BlinkD9.hex` to an Arduino pro mini (8MHz) using Sparkfun's pocket AVR programmer with AVRDude.

I changed the fuse values according to this diagram:
https://www.flickr.com/photos/15304611@N03/10585364014

Then I tried to program the board within Arduino IDE version 1.8.13, using an FTDI USB-to-Serial adaptor, with the `Blink` program.

Arduino terminal gets stuck at the synchronization stage. It seems that the STK-500 emulator cannot communicate with the board.

Am I doing something wrong? Is there any solution to this problem?

Thank you very much!

**Comment by LowPowerLab** [comment]
The fuses for 8mhz are:  ext:FE high:DC low:E2
